### PR TITLE
first step to AutoDrive interaction

### PR DESCRIPTION
**Pull request by Axel32019**
Hello @loki79uk , Please find the topics to clarify as TODO:....
Feel free to contact me.

### CODE REVIEW

**Comment by loki79uk** [comment]
Hi - thanks so much for this.  I planned to work on AD integration over Christmas, but I had some family commitments and some other bugs to work on.  Somehow it is now almost Feburary already!

It would be good to chat at some point as there are a few points that I know will need more work.  Off the top of my head:
1) It is not always guranteed that a trailer will be able to unload - e.g. if the unloading area is blocked.  This could of course be more of an issue with repeated unloading in the same location that is likely to occur with AD.
2) Most trailers can only load/unload on the left and right sides. Curtain trailers can only unload on the side where the curtain is open. Rear unloading is enabled using a specific config (for e.g. pickup trucks), and for those is there is no left or right option.
3) A pallet must fail to load before the trailer is known to be full - e.g. if it loads the last one that will fit, we must attempt to load one more object before it will be considered "full".  Even then, there could be enough space for other smaller pallets, but it will still considered full until it is either fully or partially unloaded.

**Comment by Axel32019** [comment]
1. This is always the case and could not be avoided, in the past we always unload until the vehicle stuck in the material.
2. So should the unload side some kind of a users wish, or shall we block unload if the selected side is not supported / allowed?
3. For this we might start with my dirty approach.

**Comment by loki79uk** [comment]
Okay - I will hopefully get some proper time to work on this, but coming up I have two kid's birthdays and busy (away from pc) with family commitments for all of half term week.

1. The difference with UAL is that it will fail to unload when there is no room.  I could:
    i) add an override for this behaviour for AD to always unload
    ii) return a value to let AD know that unloading failed
    iii) show a warning message that the unloading area is blocked
2. For most trailers there is a manually selected unloading side in UAL - it could be changed with an exposed function for AD, or maybe we can just use whichever side is already selected (jn UAL).  For the curtain trailers I could override the requirement for the curtain to be open, or maybe even better to open the curtain as part of the AD unloading function.
3. Yes, I think this one is hardest to do anything about - it is even more complicated with UAL since the loading happens over many game cycles (lasting several seconds).

**Comment by Axel32019** [comment]
Keep cool - private live is always 1st prio!

i) add an override for this behaviour for AD to always unload 
-> this would be my prefered solution

ii) return a value to let AD know that unloading failed 
-> this need more adaption in the unload behaviour compared to the present implementation

iii) show a warning message that the unloading area is blocked 
-> makes not really sense, as most of the times nobody will be inside the vehicle or disturbed by several warnings

For most trailers there is a manually selected unloading side in UAL - it could be changed with an exposed function for AD, 
-> I already use UniversalAutoload:ualUnload(tipSideString) to pass tipSideString with the unloading side, which works for bales

or maybe we can just use whichever side is already selected (jn UAL). 
-> This might also be an option.

For the curtain trailers I could override the requirement for the curtain to be open, or maybe even better to open the curtain as part of the AD unloading function.
Yes, I think this one is hardest to do anything about - it is even more complicated with UAL since the loading happens over many game cycles 
(lasting several seconds).
->Sound also good. If the request ualUnload(tipSideString) could not be set as side, then unload at a possible side.
For this I have implemented today the check for the curtain is closed. AD will wait even several seconds for it before continue with next action.

**Comment by loki79uk** [comment]
Hi @Axel32019 - I sent you a message on Discord, I hope that is okay.

I think I have addressed most of the points in my local working copy, but needs some more testing.  I will push the new version soon.

I wonder if you have thought about how to deal with a trailer that has both UAL and aPalletAutoloader?  I think it is fine to use UAL only when the other one is not present, but maybe it could be an AD option to select "preferred autoload method" (if available)?

**Pull request merged**
